### ISSUE TITLE
list-all isn't working

### ISSUE THREAD

**Issue by StephenTurley** [grimoh117/asdf-k6#13]
Seems like something is wrong with the `list all` feature. 

Here is what I tried:

`asdf plugin add k6`
`asdf list all k6`

The command returns no output

**Comment by StephenTurley** [comment]
I opened a PR https://github.com/grimoh/asdf-k6/pull/14 to fix this.

**Comment by gr1m0h** [comment]
Thanks.
This issue was resolved by #14 .
